package com.upb.model;
// Generated 2 oct. 2022 � 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Absences generated by hbm2java
 */
@Entity
@Table(name = "absences", catalog = "gestion_absences")
public class Absences implements java.io.Serializable {

	private int idAbsence;
	private Ecue ecue;
	private Enseignant enseignant;
	private Etudiant etudiant;
	private Justification justification;
	private Date dateabsence;
	private Date heuredebut;
	private Date heurefin;
	private Boolean etatAbsence;
	private Set<Justification> justifications = new HashSet<Justification>(0);

	public Absences() {
	}

	public Absences(int idAbsence, Ecue ecue, Enseignant enseignant, Etudiant etudiant) {
		this.idAbsence = idAbsence;
		this.ecue = ecue;
		this.enseignant = enseignant;
		this.etudiant = etudiant;
	}

	public Absences(int idAbsence, Ecue ecue, Enseignant enseignant, Etudiant etudiant, Justification justification,
			Date dateabsence, Date heuredebut, Date heurefin, Boolean etatAbsence, Set<Justification> justifications) {
		this.idAbsence = idAbsence;
		this.ecue = ecue;
		this.enseignant = enseignant;
		this.etudiant = etudiant;
		this.justification = justification;
		this.dateabsence = dateabsence;
		this.heuredebut = heuredebut;
		this.heurefin = heurefin;
		this.etatAbsence = etatAbsence;
		this.justifications = justifications;
	}

	@Id

	@Column(name = "ID_ABSENCE", unique = true, nullable = false)
	public int getIdAbsence() {
		return this.idAbsence;
	}

	public void setIdAbsence(int idAbsence) {
		this.idAbsence = idAbsence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODEECUE", nullable = false)
	public Ecue getEcue() {
		return this.ecue;
	}

	public void setEcue(Ecue ecue) {
		this.ecue = ecue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTILISATEUR", nullable = false)
	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETU_ID_UTILISATEUR", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JUSTIFICATION")
	public Justification getJustification() {
		return this.justification;
	}

	public void setJustification(Justification justification) {
		this.justification = justification;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEABSENCE", length = 10)
	public Date getDateabsence() {
		return this.dateabsence;
	}

	public void setDateabsence(Date dateabsence) {
		this.dateabsence = dateabsence;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HEUREDEBUT", length = 8)
	public Date getHeuredebut() {
		return this.heuredebut;
	}

	public void setHeuredebut(Date heuredebut) {
		this.heuredebut = heuredebut;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HEUREFIN", length = 8)
	public Date getHeurefin() {
		return this.heurefin;
	}

	public void setHeurefin(Date heurefin) {
		this.heurefin = heurefin;
	}

	@Column(name = "ETAT_ABSENCE")
	public Boolean getEtatAbsence() {
		return this.etatAbsence;
	}

	public void setEtatAbsence(Boolean etatAbsence) {
		this.etatAbsence = etatAbsence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "absences")
	public Set<Justification> getJustifications() {
		return this.justifications;
	}

	public void setJustifications(Set<Justification> justifications) {
		this.justifications = justifications;
	}

	

}
