package com.upb.model;
// Generated 2 oct. 2022 à 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "gestion_absences")
public class Administrateur implements java.io.Serializable {

	private int idUtilisateur;
	private Niveaux niveaux;
	private Utilisateur utilisateur;
	private String nomutilisateur;
	private String prenomsutilisateur;
	private Long telephoneutilisateur;
	private String emailadministrateur;
	private Set<Niveaux> niveauxes = new HashSet<Niveaux>(0);

	public Administrateur() {
	}

	public Administrateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Administrateur(Niveaux niveaux, Utilisateur utilisateur, String nomutilisateur, String prenomsutilisateur,
			Long telephoneutilisateur, String emailadministrateur, Set<Niveaux> niveauxes) {
		this.niveaux = niveaux;
		this.utilisateur = utilisateur;
		this.nomutilisateur = nomutilisateur;
		this.prenomsutilisateur = prenomsutilisateur;
		this.telephoneutilisateur = telephoneutilisateur;
		this.emailadministrateur = emailadministrateur;
		this.niveauxes = niveauxes;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID_UTILISATEUR", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NIVEAU")
	public Niveaux getNiveaux() {
		return this.niveaux;
	}

	public void setNiveaux(Niveaux niveaux) {
		this.niveaux = niveaux;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "NOMUTILISATEUR", length = 30)
	public String getNomutilisateur() {
		return this.nomutilisateur;
	}

	public void setNomutilisateur(String nomutilisateur) {
		this.nomutilisateur = nomutilisateur;
	}

	@Column(name = "PRENOMSUTILISATEUR", length = 50)
	public String getPrenomsutilisateur() {
		return this.prenomsutilisateur;
	}

	public void setPrenomsutilisateur(String prenomsutilisateur) {
		this.prenomsutilisateur = prenomsutilisateur;
	}

	@Column(name = "TELEPHONEUTILISATEUR")
	public Long getTelephoneutilisateur() {
		return this.telephoneutilisateur;
	}

	public void setTelephoneutilisateur(Long telephoneutilisateur) {
		this.telephoneutilisateur = telephoneutilisateur;
	}

	@Column(name = "EMAILADMINISTRATEUR", length = 50)
	public String getEmailadministrateur() {
		return this.emailadministrateur;
	}

	public void setEmailadministrateur(String emailadministrateur) {
		this.emailadministrateur = emailadministrateur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrateur")
	public Set<Niveaux> getNiveauxes() {
		return this.niveauxes;
	}

	public void setNiveauxes(Set<Niveaux> niveauxes) {
		this.niveauxes = niveauxes;
	}

}
