package com.upb.model;
// Generated 2 oct. 2022 à 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnneeAcademique generated by hbm2java
 */
@Entity
@Table(name = "annee_academique", catalog = "gestion_absences")
public class AnneeAcademique implements java.io.Serializable {

	private int idAnneeAcademique;
	private Date dateDebut;
	private Date dateFin;
	private Set<Semestre> semestres = new HashSet<Semestre>(0);

	public AnneeAcademique() {
	}

	public AnneeAcademique(int idAnneeAcademique) {
		this.idAnneeAcademique = idAnneeAcademique;
	}

	public AnneeAcademique(int idAnneeAcademique, Date dateDebut, Date dateFin, Set<Semestre> semestres) {
		this.idAnneeAcademique = idAnneeAcademique;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.semestres = semestres;
	}

	@Id

	@Column(name = "ID_ANNEE_ACADEMIQUE", unique = true, nullable = false)
	public int getIdAnneeAcademique() {
		return this.idAnneeAcademique;
	}

	public void setIdAnneeAcademique(int idAnneeAcademique) {
		this.idAnneeAcademique = idAnneeAcademique;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeAcademique")
	public Set<Semestre> getSemestres() {
		return this.semestres;
	}

	public void setSemestres(Set<Semestre> semestres) {
		this.semestres = semestres;
	}

}
