package com.upb.model;
// Generated 2 oct. 2022 � 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name = "enseignant", catalog = "gestion_absences")
public class Enseignant implements java.io.Serializable {

	private int idUtilisateur;
	private Utilisateur utilisateur;
	private String nomutilisateur;
	private String prenomsutilisateur;
	private Long telephoneutilisateur;
	private String emailenseignant;
	private String specialiteenseignant;
	private Set<Absences> absenceses = new HashSet<Absences>(0);

	public Enseignant() {
	}

	public Enseignant(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Enseignant(Utilisateur utilisateur, String nomutilisateur, String prenomsutilisateur,
			Long telephoneutilisateur, String emailenseignant, String specialiteenseignant, Set<Absences> absenceses) {
		this.utilisateur = utilisateur;
		this.nomutilisateur = nomutilisateur;
		this.prenomsutilisateur = prenomsutilisateur;
		this.telephoneutilisateur = telephoneutilisateur;
		this.emailenseignant = emailenseignant;
		this.specialiteenseignant = specialiteenseignant;
		this.absenceses = absenceses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID_UTILISATEUR", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "NOMUTILISATEUR", length = 30)
	public String getNomutilisateur() {
		return this.nomutilisateur;
	}

	public void setNomutilisateur(String nomutilisateur) {
		this.nomutilisateur = nomutilisateur;
	}

	@Column(name = "PRENOMSUTILISATEUR", length = 50)
	public String getPrenomsutilisateur() {
		return this.prenomsutilisateur;
	}

	public void setPrenomsutilisateur(String prenomsutilisateur) {
		this.prenomsutilisateur = prenomsutilisateur;
	}

	@Column(name = "TELEPHONEUTILISATEUR")
	public Long getTelephoneutilisateur() {
		return this.telephoneutilisateur;
	}

	public void setTelephoneutilisateur(Long telephoneutilisateur) {
		this.telephoneutilisateur = telephoneutilisateur;
	}

	@Column(name = "EMAILENSEIGNANT", length = 30)
	public String getEmailenseignant() {
		return this.emailenseignant;
	}

	public void setEmailenseignant(String emailenseignant) {
		this.emailenseignant = emailenseignant;
	}

	@Column(name = "SPECIALITEENSEIGNANT", length = 50)
	public String getSpecialiteenseignant() {
		return this.specialiteenseignant;
	}

	public void setSpecialiteenseignant(String specialiteenseignant) {
		this.specialiteenseignant = specialiteenseignant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enseignant")
	public Set<Absences> getAbsenceses() {
		return this.absenceses;
	}

	public void setAbsenceses(Set<Absences> absenceses) {
		this.absenceses = absenceses;
	}

}
