package com.upb.model;
// Generated 2 oct. 2022 à 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "gestion_absences")
public class Etudiant implements java.io.Serializable {

	private int idUtilisateur;
	private Filiere filiere;
	private Niveaux niveaux;
	private Parent parent;
	private Utilisateur utilisateur;
	private String nomutilisateur;
	private String prenomsutilisateur;
	private Long telephoneutilisateur;
	private String matriculeetudiant;
	private Date datedenaissance;
	private Set<Absences> absenceses = new HashSet<Absences>(0);

	public Etudiant() {
	}

	public Etudiant(Filiere filiere, Niveaux niveaux, Parent parent, Utilisateur utilisateur) {
		this.filiere = filiere;
		this.niveaux = niveaux;
		this.parent = parent;
		this.utilisateur = utilisateur;
	}

	public Etudiant(Filiere filiere, Niveaux niveaux, Parent parent, Utilisateur utilisateur, String nomutilisateur,
			String prenomsutilisateur, Long telephoneutilisateur, String matriculeetudiant, Date datedenaissance,
			Set<Absences> absenceses) {
		this.filiere = filiere;
		this.niveaux = niveaux;
		this.parent = parent;
		this.utilisateur = utilisateur;
		this.nomutilisateur = nomutilisateur;
		this.prenomsutilisateur = prenomsutilisateur;
		this.telephoneutilisateur = telephoneutilisateur;
		this.matriculeetudiant = matriculeetudiant;
		this.datedenaissance = datedenaissance;
		this.absenceses = absenceses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "utilisateur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID_UTILISATEUR", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FILIERE", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NIVEAU", nullable = false)
	public Niveaux getNiveaux() {
		return this.niveaux;
	}

	public void setNiveaux(Niveaux niveaux) {
		this.niveaux = niveaux;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARENT", nullable = false)
	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "NOMUTILISATEUR", length = 30)
	public String getNomutilisateur() {
		return this.nomutilisateur;
	}

	public void setNomutilisateur(String nomutilisateur) {
		this.nomutilisateur = nomutilisateur;
	}

	@Column(name = "PRENOMSUTILISATEUR", length = 50)
	public String getPrenomsutilisateur() {
		return this.prenomsutilisateur;
	}

	public void setPrenomsutilisateur(String prenomsutilisateur) {
		this.prenomsutilisateur = prenomsutilisateur;
	}

	@Column(name = "TELEPHONEUTILISATEUR")
	public Long getTelephoneutilisateur() {
		return this.telephoneutilisateur;
	}

	public void setTelephoneutilisateur(Long telephoneutilisateur) {
		this.telephoneutilisateur = telephoneutilisateur;
	}

	@Column(name = "MATRICULEETUDIANT", length = 20)
	public String getMatriculeetudiant() {
		return this.matriculeetudiant;
	}

	public void setMatriculeetudiant(String matriculeetudiant) {
		this.matriculeetudiant = matriculeetudiant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEDENAISSANCE", length = 10)
	public Date getDatedenaissance() {
		return this.datedenaissance;
	}

	public void setDatedenaissance(Date datedenaissance) {
		this.datedenaissance = datedenaissance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Absences> getAbsenceses() {
		return this.absenceses;
	}

	public void setAbsenceses(Set<Absences> absenceses) {
		this.absenceses = absenceses;
	}

}
