package com.upb.model;
// Generated 2 oct. 2022 à 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Justification generated by hbm2java
 */
@Entity
@Table(name = "justification", catalog = "gestion_absences")
public class Justification implements java.io.Serializable {

	private int idJustification;
	private Absences absences;
	private Date datejustification;
	private String motifjustification;
	private Boolean validation;
	private String fichierjustification;
	private Set<Absences> absenceses = new HashSet<Absences>(0);

	public Justification() {
	}

	public Justification(int idJustification, Absences absences) {
		this.idJustification = idJustification;
		this.absences = absences;
	}

	public Justification(int idJustification, Absences absences, Date datejustification, String motifjustification,
			Boolean validation, String fichierjustification, Set<Absences> absenceses) {
		this.idJustification = idJustification;
		this.absences = absences;
		this.datejustification = datejustification;
		this.motifjustification = motifjustification;
		this.validation = validation;
		this.fichierjustification = fichierjustification;
		this.absenceses = absenceses;
	}

	@Id

	@Column(name = "ID_JUSTIFICATION", unique = true, nullable = false)
	public int getIdJustification() {
		return this.idJustification;
	}

	public void setIdJustification(int idJustification) {
		this.idJustification = idJustification;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ABSENCE", nullable = false)
	public Absences getAbsences() {
		return this.absences;
	}

	public void setAbsences(Absences absences) {
		this.absences = absences;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEJUSTIFICATION", length = 10)
	public Date getDatejustification() {
		return this.datejustification;
	}

	public void setDatejustification(Date datejustification) {
		this.datejustification = datejustification;
	}

	@Column(name = "MOTIFJUSTIFICATION", length = 100)
	public String getMotifjustification() {
		return this.motifjustification;
	}

	public void setMotifjustification(String motifjustification) {
		this.motifjustification = motifjustification;
	}

	@Column(name = "VALIDATION")
	public Boolean getValidation() {
		return this.validation;
	}

	public void setValidation(Boolean validation) {
		this.validation = validation;
	}

	@Column(name = "FICHIERJUSTIFICATION", length = 50)
	public String getFichierjustification() {
		return this.fichierjustification;
	}

	public void setFichierjustification(String fichierjustification) {
		this.fichierjustification = fichierjustification;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "justification")
	public Set<Absences> getAbsenceses() {
		return this.absenceses;
	}

	public void setAbsenceses(Set<Absences> absenceses) {
		this.absenceses = absenceses;
	}

}
