package com.upb.model;
// Generated 2 oct. 2022 à 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "gestion_absences")
public class Semestre implements java.io.Serializable {

	private int idSemestre;
	private AnneeAcademique anneeAcademique;
	private String intitulesemestre;
	private Set<Ecue> ecues = new HashSet<Ecue>(0);

	public Semestre() {
	}

	public Semestre(int idSemestre, AnneeAcademique anneeAcademique) {
		this.idSemestre = idSemestre;
		this.anneeAcademique = anneeAcademique;
	}

	public Semestre(int idSemestre, AnneeAcademique anneeAcademique, String intitulesemestre, Set<Ecue> ecues) {
		this.idSemestre = idSemestre;
		this.anneeAcademique = anneeAcademique;
		this.intitulesemestre = intitulesemestre;
		this.ecues = ecues;
	}

	@Id

	@Column(name = "ID_SEMESTRE", unique = true, nullable = false)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ANNEE_ACADEMIQUE", nullable = false)
	public AnneeAcademique getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@Column(name = "INTITULESEMESTRE", length = 100)
	public String getIntitulesemestre() {
		return this.intitulesemestre;
	}

	public void setIntitulesemestre(String intitulesemestre) {
		this.intitulesemestre = intitulesemestre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semestre")
	public Set<Ecue> getEcues() {
		return this.ecues;
	}

	public void setEcues(Set<Ecue> ecues) {
		this.ecues = ecues;
	}

}
