package com.upb.model;
// Generated 2 oct. 2022 à 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserAuthorization generated by hbm2java
 */
@Entity
@Table(name = "user_authorization", catalog = "gestion_absences")
public class UserAuthorization implements java.io.Serializable {

	private int idAuthorization;
	private String libelleauthorization;
	private Set<UserAuthentification> userAuthentifications = new HashSet<UserAuthentification>(0);

	public UserAuthorization() {
	}

	public UserAuthorization(int idAuthorization) {
		this.idAuthorization = idAuthorization;
	}

	public UserAuthorization(int idAuthorization, String libelleauthorization,
			Set<UserAuthentification> userAuthentifications) {
		this.idAuthorization = idAuthorization;
		this.libelleauthorization = libelleauthorization;
		this.userAuthentifications = userAuthentifications;
	}

	@Id

	@Column(name = "ID_AUTHORIZATION", unique = true, nullable = false)
	public int getIdAuthorization() {
		return this.idAuthorization;
	}

	public void setIdAuthorization(int idAuthorization) {
		this.idAuthorization = idAuthorization;
	}

	@Column(name = "LIBELLEAUTHORIZATION", length = 30)
	public String getLibelleauthorization() {
		return this.libelleauthorization;
	}

	public void setLibelleauthorization(String libelleauthorization) {
		this.libelleauthorization = libelleauthorization;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAuthorization")
	public Set<UserAuthentification> getUserAuthentifications() {
		return this.userAuthentifications;
	}

	public void setUserAuthentifications(Set<UserAuthentification> userAuthentifications) {
		this.userAuthentifications = userAuthentifications;
	}

}
