package com.upb.model;
// Generated 2 oct. 2022 à 22:08:38 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAuthentification generated by hbm2java
 */
@Entity
@Table(name = "user_authentification", catalog = "gestion_absences")
public class UserAuthentification implements java.io.Serializable {

	private int idUser;
	private UserAuthorization userAuthorization;
	private Utilisateur utilisateur;
	private String login;
	private String password;

	public UserAuthentification() {
	}

	public UserAuthentification(int idUser, UserAuthorization userAuthorization, Utilisateur utilisateur) {
		this.idUser = idUser;
		this.userAuthorization = userAuthorization;
		this.utilisateur = utilisateur;
	}

	public UserAuthentification(int idUser, UserAuthorization userAuthorization, Utilisateur utilisateur, String login,
			String password) {
		this.idUser = idUser;
		this.userAuthorization = userAuthorization;
		this.utilisateur = utilisateur;
		this.login = login;
		this.password = password;
	}

	@Id

	@Column(name = "ID_USER", unique = true, nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AUTHORIZATION", nullable = false)
	public UserAuthorization getUserAuthorization() {
		return this.userAuthorization;
	}

	public void setUserAuthorization(UserAuthorization userAuthorization) {
		this.userAuthorization = userAuthorization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_UTILISATEUR", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "LOGIN", length = 30)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
