package com.upb.model;
// Generated 2 oct. 2022 � 22:08:38 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "gestion_absences")
public class Utilisateur implements java.io.Serializable {

	private int idUtilisateur;
	private String nomutilisateur;
	private String prenomsutilisateur;
	private Long telephoneutilisateur;
	private Etudiant etudiant;
	private Set<UserAuthentification> userAuthentifications = new HashSet<UserAuthentification>(0);
	private Enseignant enseignant;
	private Administrateur administrateur;

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public Utilisateur(int idUtilisateur, String nomutilisateur, String prenomsutilisateur, Long telephoneutilisateur,
			Etudiant etudiant, Set<UserAuthentification> userAuthentifications, Enseignant enseignant,
			Administrateur administrateur) {
		this.idUtilisateur = idUtilisateur;
		this.nomutilisateur = nomutilisateur;
		this.prenomsutilisateur = prenomsutilisateur;
		this.telephoneutilisateur = telephoneutilisateur;
		this.etudiant = etudiant;
		this.userAuthentifications = userAuthentifications;
		this.enseignant = enseignant;
		this.administrateur = administrateur;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_UTILISATEUR", unique = true, nullable = false)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "NOMUTILISATEUR", length = 30)
	public String getNomutilisateur() {
		return this.nomutilisateur;
	}

	public void setNomutilisateur(String nomutilisateur) {
		this.nomutilisateur = nomutilisateur;
	}

	@Column(name = "PRENOMSUTILISATEUR", length = 50)
	public String getPrenomsutilisateur() {
		return this.prenomsutilisateur;
	}

	public void setPrenomsutilisateur(String prenomsutilisateur) {
		this.prenomsutilisateur = prenomsutilisateur;
	}

	@Column(name = "TELEPHONEUTILISATEUR")
	public Long getTelephoneutilisateur() {
		return this.telephoneutilisateur;
	}

	public void setTelephoneutilisateur(Long telephoneutilisateur) {
		this.telephoneutilisateur = telephoneutilisateur;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<UserAuthentification> getUserAuthentifications() {
		return this.userAuthentifications;
	}

	public void setUserAuthentifications(Set<UserAuthentification> userAuthentifications) {
		this.userAuthentifications = userAuthentifications;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Administrateur getAdministrateur() {
		return this.administrateur;
	}

	public void setAdministrateur(Administrateur administrateur) {
		this.administrateur = administrateur;
	}

}
